version: '3.8'

services:
  erigon:
    image: thorax/erigon:latest
    container_name: erigon
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - /mnt/blockchain-disk/erigon:/home/erigon/.local/share/erigon
      - /mnt/lighthouse-data/lighthouse-hot/ethereum/geth/jwtsecret:/home/erigon/jwtsecret:ro
    environment:
      - ERIGON_DATADIR=/home/erigon/.local/share/erigon
    command: >
      --datadir=/home/erigon/.local/share/erigon
      --chain=mainnet
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,erigon,web3,net,debug,trace,txpool,parity,ots
      --http.corsdomain=*
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.api=eth,erigon,web3,net,debug,trace,txpool,parity,ots
      --private.api.addr=0.0.0.0:9090
      --torrent.port=42068
      --torrent.upload.rate=512mb
      --torrent.download.rate=512mb
      --torrent.conns=100
      --p2p
      --maxpeers=100
      --nat=extip:$(curl -s ifconfig.me)
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
      nproc:
        soft: 1048576
        hard: 1048576
    shm_size: 2g
    deploy:
      resources:
        limits:
          memory: 120G
        reservations:
          memory: 100G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ethereum-prometheus:
    image: prom/prometheus:latest
    container_name: ethereum-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /home/vovkes/JavaMicroDeFi/blockchain-sync-service/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  ethereum-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ethereum-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ethereum-data/prometheus
  zookeeper_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ethereum-data/zookeeper
