version: '3.8'

services:
  # Apache Kafka Infrastructure
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - defimon-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - defimon-network

  # MongoDB for chain data storage
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: defimon123
      MONGO_INITDB_DATABASE: chaindata
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - defimon-network

  # API Gateway (Spring Cloud Gateway)
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - defimon-network

  # Blockchain Synchronization Service (Rust)
  blockchain-sync:
    build: ./blockchain-sync-service
    container_name: blockchain-sync
    ports:
      - "9090:9090"  # Prometheus metrics port
    environment:
      - KAFKA_BROKERS=kafka:29092
      - MONGODB_URI=mongodb://admin:defimon123@mongodb:27017/chaindata?authSource=admin
      - ETH_RPC_URL=http://host.docker.internal:8545
      - METRICS_ADDR=0.0.0.0:9090
      - RUST_LOG=info
      - BLOCKCHAIN_DATA_PATH=/mnt/blockchain-disk
    volumes:
      - /mnt/blockchain-disk:/mnt/blockchain-disk:ro
    depends_on:
      - kafka
      - mongodb
    networks:
      - defimon-network

  # Transaction Signing Service (Rust)
  transaction-signing:
    build: ./transaction-signing-service
    container_name: transaction-signing
    ports:
      - "8082:8082"  # API port
    environment:
      - KAFKA_BROKERS=kafka:29092
      - RUST_LOG=info
    depends_on:
      - kafka
    networks:
      - defimon-network

  # Math Computing Service (Rust)
  math-computing:
    build: ./math-computing-service
    container_name: math-computing
    ports:
      - "8083:8083"  # API port
    environment:
      - KAFKA_BROKERS=kafka:29092
      - RUST_LOG=info
    depends_on:
      - kafka
    networks:
      - defimon-network

  # Data Aggregation Service (Rust)
  data-aggregation:
    build: ./data-aggregation-service
    container_name: data-aggregation
    ports:
      - "8084:8084"  # API port
    environment:
      - KAFKA_BROKERS=kafka:29092
      - MONGODB_URI=mongodb://admin:defimon123@mongodb:27017/chaindata?authSource=admin
      - RUST_LOG=info
    depends_on:
      - kafka
      - mongodb
    networks:
      - defimon-network

  # Simple Rust Metrics Service (for testing)
  simple-metrics:
    build: ./simple-rust-metrics-service
    container_name: simple-metrics
    ports:
      - "8090:8080"  # API port
    networks:
      - defimon-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./blockchain-sync-service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - defimon-network

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=defimon123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./blockchain-sync-service/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./blockchain-sync-service/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - defimon-network

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  defimon-network:
    driver: bridge
