apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://ETHEREUM_mainnet_full-prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
