version: '3.8'

services:
  erigon:
    image: erigontech/erigon:latest
    container_name: erigon-archive-node
    restart: unless-stopped
    ports:
      - "30303:30303"     # P2P port
      - "8545:8545"       # HTTP RPC
      - "8546:8546"       # WebSocket RPC  
      - "8551:8551"       # Engine API (for consensus layer)
      - "6060:6060"       # Metrics
    volumes:
      - /mnt/sata18tb/erigon-hot:/home/erigon/.local/share/erigon
      - ./erigon-config:/config
    command: [
      "erigon",
      "--datadir=/home/erigon/.local/share/erigon",
      "--chain=mainnet",
      "--http",
      "--http.addr=0.0.0.0",
      "--http.port=8545",
      "--http.api=eth,debug,net,trace,web3,erigon",
      "--http.vhosts=*",
      "--http.corsdomain=*",
      "--authrpc.addr=0.0.0.0",
      "--authrpc.port=8551",
      "--authrpc.vhosts=*",
      "--authrpc.jwtsecret=/config/jwt.hex",
      "--metrics",
      "--metrics.addr=0.0.0.0",
      "--metrics.port=6060"
    ]
    networks:
      - ethereum-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8545 -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_syncing\",\"params\":[],\"id\":1}' || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s

networks:
  ethereum-net:
    driver: bridge
