global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'erigon'
    static_configs:
      - targets: ['erigon:6060']
    scrape_interval: 10s
    metrics_path: /debug/metrics/prometheus

  - job_name: 'lighthouse-beacon'
    static_configs:
      - targets: ['lighthouse:5054']
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
