{
 "title": "Ethereum Sync Status",
 "tags": [
  "ethereum",
  "blockchain",
  "sync"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ethereum Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"erigon\"}",
     "legendFormat": "Erigon Status"
    },
    {
     "expr": "up{job=\"lighthouse-beacon\"}",
     "legendFormat": "Lighthouse Status"
    }
   ]
  },
  {
   "title": "Lighthouse Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "active_validators_count", "legendFormat": "Active Validators" }
   ]
  },
  {
   "title": "Lighthouse Async Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "async_tasks_count", "legendFormat": "{{async_task_count}}" }
   ]
  }
 ]
}