[package]
name = "simple-rust-metrics-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
serde_json = "1.0"
prometheus = "0.13"
chrono = { version = "0.4", features = ["serde"] }
